name: Build and publish
run-name: ${{ gitea.actor }} is runs ci pipeline
on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."git.bhasher.com"]
              http = true
              insecure = true

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: git.bhasher.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            git.bhasher.com/bhasher/tg2:latest

      # - name: Deploy
      #   run: |
      #     curl -X POST https://portainer.bxl.bhasher.com/api/webhooks/
